call sqlhydra-mssql-net8.bat
call sqlhydra-mssql-net9.bat
call sqlhydra-mssql-net10.bat
call sqlhydra-npgsql-net8.bat
call sqlhydra-npgsql-net9.bat
call sqlhydra-npgsql-net10.bat
call sqlhydra-oracle-net8.bat
call sqlhydra-oracle-net9.bat
call sqlhydra-oracle-net10.bat
call sqlhydra-sqlite-net8.bat
call sqlhydra-sqlite-net9.bat
call sqlhydra-sqlite-net10.bat
