// This code was generated by `SqlHydra.Sqlite` -- v4.0.1.
namespace Symphony.Northwind

open SqlHydra
open SqlHydra.Query

module Version =
    let cli = System.Version(4, 0, 1)
    let ns = "Symphony.Northwind"
    SqlHydra.Query.VersionCheck.assertIsCompatible cli ns

module main =

    type ``Alphabetical list of products`` =
        { ProductID: Option<int64>
          ProductName: Option<string>
          SupplierID: Option<int64>
          CategoryID: Option<int64>
          QuantityPerUnit: Option<string>
          UnitPrice: Option<decimal>
          UnitsInStock: Option<int64>
          UnitsOnOrder: Option<int64>
          ReorderLevel: Option<int64>
          Discontinued: Option<string>
          CategoryName: Option<string> }

    type Categories =
        { CategoryID: int64
          CategoryName: Option<string>
          Description: Option<string>
          Picture: Option<byte[]> }

    type ``Category Sales for 1997`` = { CategoryName: Option<string> }

    type ``Current Product List`` =
        { ProductID: Option<int64>
          ProductName: Option<string> }

    type ``Customer and Suppliers by City`` =
        { City: Option<string>
          CompanyName: Option<string>
          ContactName: Option<string> }

    type CustomerCustomerDemo =
        { CustomerID: string
          CustomerTypeID: string }

    type CustomerDemographics =
        { CustomerTypeID: string
          CustomerDesc: Option<string> }

    type Customers =
        { CustomerID: Option<string>
          CompanyName: Option<string>
          ContactName: Option<string>
          ContactTitle: Option<string>
          Address: Option<string>
          City: Option<string>
          Region: Option<string>
          PostalCode: Option<string>
          Country: Option<string>
          Phone: Option<string>
          Fax: Option<string> }

    type EmployeeTerritories =
        { EmployeeID: int64
          TerritoryID: string }

    type Employees =
        { EmployeeID: int64
          LastName: Option<string>
          FirstName: Option<string>
          Title: Option<string>
          TitleOfCourtesy: Option<string>
          BirthDate: Option<System.DateOnly>
          HireDate: Option<System.DateOnly>
          Address: Option<string>
          City: Option<string>
          Region: Option<string>
          PostalCode: Option<string>
          Country: Option<string>
          HomePhone: Option<string>
          Extension: Option<string>
          Photo: Option<byte[]>
          Notes: Option<string>
          ReportsTo: Option<int64>
          PhotoPath: Option<string> }

    type Invoices =
        { ShipName: Option<string>
          ShipAddress: Option<string>
          ShipCity: Option<string>
          ShipRegion: Option<string>
          ShipPostalCode: Option<string>
          ShipCountry: Option<string>
          CustomerID: Option<string>
          CustomerName: Option<string>
          Address: Option<string>
          City: Option<string>
          Region: Option<string>
          PostalCode: Option<string>
          Country: Option<string>
          OrderID: Option<int64>
          OrderDate: Option<System.DateTime>
          RequiredDate: Option<System.DateTime>
          ShippedDate: Option<System.DateTime>
          ShipperName: Option<string>
          ProductID: Option<int64>
          ProductName: Option<string>
          UnitPrice: Option<decimal>
          Quantity: Option<int64>
          Discount: Option<double>
          Freight: Option<decimal> }

    type ``Order Details`` =
        { OrderID: int64
          ProductID: int64
          UnitPrice: global.Symphony.Bridge.Spec.Refined<decimal, global.Symphony.Bridge.Spec.GreaterThanOrEqualToZero>
          Quantity: global.Symphony.Bridge.Spec.Refined<int64, global.Symphony.Bridge.Spec.GreaterThanZero>
          Discount: global.Symphony.Bridge.Spec.Refined<double, global.Symphony.Bridge.Spec.BetweenZeroAndOne> }

    type ``Order Details Extended`` =
        { OrderID: Option<int64>
          ProductID: Option<int64>
          ProductName: Option<string>
          UnitPrice: Option<decimal>
          Quantity: Option<int64>
          Discount: Option<double> }

    type ``Order Subtotals`` = { OrderID: Option<int64> }

    type Orders =
        { OrderID: int64
          CustomerID: Option<string>
          EmployeeID: Option<int64>
          OrderDate: Option<System.DateTime>
          RequiredDate: Option<System.DateTime>
          ShippedDate: Option<System.DateTime>
          ShipVia: Option<int64>
          Freight: Option<decimal>
          ShipName: Option<string>
          ShipAddress: Option<string>
          ShipCity: Option<string>
          ShipRegion: Option<string>
          ShipPostalCode: Option<string>
          ShipCountry: Option<string> }

    type ``Orders Qry`` =
        { OrderID: Option<int64>
          CustomerID: Option<string>
          EmployeeID: Option<int64>
          OrderDate: Option<System.DateTime>
          RequiredDate: Option<System.DateTime>
          ShippedDate: Option<System.DateTime>
          ShipVia: Option<int64>
          Freight: Option<decimal>
          ShipName: Option<string>
          ShipAddress: Option<string>
          ShipCity: Option<string>
          ShipRegion: Option<string>
          ShipPostalCode: Option<string>
          ShipCountry: Option<string>
          CompanyName: Option<string>
          Address: Option<string>
          City: Option<string>
          Region: Option<string>
          PostalCode: Option<string>
          Country: Option<string> }

    type ``Product Sales for 1997`` =
        { CategoryName: Option<string>
          ProductName: Option<string> }

    type ProductDetails_V =
        { ProductID: Option<int64>
          ProductName: Option<string>
          SupplierID: Option<int64>
          CategoryID: Option<int64>
          QuantityPerUnit: Option<string>
          UnitPrice: Option<decimal>
          UnitsInStock: Option<int64>
          UnitsOnOrder: Option<int64>
          ReorderLevel: Option<int64>
          Discontinued: Option<string>
          CategoryName: Option<string>
          CategoryDescription: Option<string>
          SupplierName: Option<string>
          SupplierRegion: Option<string> }

    type Products =
        { ProductID: int64
          ProductName: string
          SupplierID: Option<int64>
          CategoryID: Option<int64>
          QuantityPerUnit: Option<string>
          UnitPrice:
              Option<global.Symphony.Bridge.Spec.Refined<decimal, global.Symphony.Bridge.Spec.GreaterThanOrEqualToZero>>
          UnitsInStock:
              Option<global.Symphony.Bridge.Spec.Refined<int64, global.Symphony.Bridge.Spec.GreaterThanOrEqualToZero>>
          UnitsOnOrder:
              Option<global.Symphony.Bridge.Spec.Refined<int64, global.Symphony.Bridge.Spec.GreaterThanOrEqualToZero>>
          ReorderLevel:
              Option<global.Symphony.Bridge.Spec.Refined<int64, global.Symphony.Bridge.Spec.GreaterThanOrEqualToZero>>
          Discontinued: string }

    type ``Products Above Average Price`` =
        { ProductName: Option<string>
          UnitPrice: Option<decimal> }

    type ``Products by Category`` =
        { CategoryName: Option<string>
          ProductName: Option<string>
          QuantityPerUnit: Option<string>
          UnitsInStock: Option<int64>
          Discontinued: Option<string> }

    type ``Quarterly Orders`` =
        { CustomerID: Option<string>
          CompanyName: Option<string>
          City: Option<string>
          Country: Option<string> }

    type Regions =
        { RegionID: int64
          RegionDescription: string }

    type ``Sales Totals by Amount`` =
        { OrderID: Option<int64>
          CompanyName: Option<string>
          ShippedDate: Option<System.DateTime> }

    type ``Sales by Category`` =
        { CategoryID: Option<int64>
          CategoryName: Option<string>
          ProductName: Option<string> }

    type Shippers =
        { ShipperID: int64
          CompanyName: string
          Phone: Option<string> }

    type ``Summary of Sales by Quarter`` =
        { ShippedDate: Option<System.DateTime>
          OrderID: Option<int64> }

    type ``Summary of Sales by Year`` =
        { ShippedDate: Option<System.DateTime>
          OrderID: Option<int64> }

    type Suppliers =
        { SupplierID: int64
          CompanyName: string
          ContactName: Option<string>
          ContactTitle: Option<string>
          Address: Option<string>
          City: Option<string>
          Region: Option<string>
          PostalCode: Option<string>
          Country: Option<string>
          Phone: Option<string>
          Fax: Option<string>
          HomePage: Option<string> }

    type Territories =
        { TerritoryID: string
          TerritoryDescription: string
          RegionID: int64 }


type QueryContextFactory =
    { OpenContext: unit -> QueryContext
      OpenContextAsync: unit -> System.Threading.Tasks.Task<QueryContext> }
    // This provider holds no factory-level resources; each connection is owned and disposed by its QueryContext.
    member _.Dispose() = ()

    interface System.IDisposable with
        member this.Dispose() = this.Dispose()

    interface IQueryContextFactory with
        member this.OpenContextAsync() = this.OpenContextAsync()

    static member Create(connectionString: string, ?sqlLogger) =
        let emitter = SqlHydra.Query.SqliteEmitter()

        let createConn () : System.Data.Common.DbConnection =
            new Microsoft.Data.Sqlite.SqliteConnection(connectionString)

        let openContext () =
            let conn = createConn ()
            conn.Open()
            let ctx = new QueryContext(conn, emitter)
            sqlLogger |> Option.iter (fun logger -> ctx.Logger <- logger)
            ctx

        let openContextAsync () =
            task {
                let conn = createConn ()
                do! conn.OpenAsync()
                let ctx = new QueryContext(conn, emitter)
                sqlLogger |> Option.iter (fun logger -> ctx.Logger <- logger)
                return ctx
            }

        { OpenContext = openContext
          OpenContextAsync = openContextAsync }
